name: 01-ec2-3tier-dev CD

on: 
    push:
        branches: 
            - main
        paths:
            - '01-ec2-3tier/dev/**'
            - '01-ec2-3tier/modules/**'
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs: 
    plan:
        uses: ./.github/workflows/reusable-terraform-cd-dev.yaml
        with:
            working-directory: 01-ec2-3tier/dev/