name: Global Infrastructure CI

on: 
    pull_request:
        branches: 
            - main
        paths:
            - 'global/**'
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    pull-requests: write
        
jobs: 
    plan:
      uses: ./.github/workflows/reusable-terraform-ci.yaml
      with: 
        working-directory: global/
    